Movie/urls.py
from django.conf.urls import url
from . import views

app_name = 'movie'

urlpatterns = [
    url(r'^$', views.home_view, name='home'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^register/', views.register_view, name='register'),
    url(r'^search/$', views.search_view, name='search'),
    url(r'^account/', views.account_view, name='account'),
    url(r'^movie/(?P<movie_id>[0-9]+)/$', views.movie_view, name='movie'),
    url(r'^like/(?P<movie_id>[0-9]+)/$', views.like_movie, name='like'),
    url(r'^dislike/(?P<movie_id>[0-9]+)/$', views.dislike_movie, name='dislike')
]

MovieDB/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('Movie.urls')),
]

Movie/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Movie(models.Model):
    movie_id = models.IntegerField(unique=True)
    title = models.CharField(max_length=150)
    cover_url = models.CharField(max_length=400)
    rating = models.DecimalField(max_digits=4, decimal_places=1)

class Like(models.Model):
    movie = models.ForeignKey(Movie)
    user = models.ForeignKey(User)

Movie/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
import datetime
from models import *
from django.db.models import Q
from . import context_builders
import helpers


def home_view(request):
    template = 'home_page.html'
    context = context_builders.home_page_context(request)

    return render(request, template, context)


def search_view(request):
    template = 'search_page.html'
    page_context = context_builders.search_page_context(request)
    if page_context:
        context = {
            'movies': page_context[0],
            'counter': page_context[1],
            'page': page_context[2],
            'next_page': page_context[2] + 1,
            'prev_page': page_context[2] - 1,
            'start_row': [1, 5, 9, 13, 17],
            'end_row': [4, 8, 12, 16, 20]
        }
    else:
        context = {
            'error': True
        }
    return render(request, template, context)


def movie_view(request, movie_id):
    template = 'movie_page.html'
    context = context_builders.movie_page_context(request, movie_id)
    return render(request, template, context)


def account_view(request):
    template = 'account_page.html'

    if request.user.is_authenticated():
        context = {
            'movies': request.user.like_set.all(),
        }
        return render(request, template, context)
    return home_view(request)


def like_movie(request, movie_id):
    if request.user.is_authenticated():
        #Check is already exist
        movie = Movie.objects.filter(movie_id=movie_id).first()
        if not movie:
            movie = helpers.add_movie_to_db(movie_id)
        #Check is not liked
        like = Like.objects.filter(movie=movie,user=request.user)
        if not like:
            like = Like(
                movie=movie,
                user=request.user,
            )
            like.save()
    return movie_view(request, movie_id)


def dislike_movie(request, movie_id):
    if request.user.is_authenticated:
        movie = Movie.objects.filter(movie_id=movie_id)
        like = Like.objects.filter(movie=movie, user=request.user)
        like.delete()
    return movie_view(request, movie_id)


def login_view(request):
    template = 'login_page.html'

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return home_view(request)
        return render(request, template)
    return render(request, template)


def logout_view(request):
    logout(request)
    return home_view(request)


def register_view(request):
    if request.method == "POST":
        username = request.POST['register_username']
        password = request.POST['register_password']
        confirm_password = request.POST['confirm_password']
        user = User.objects.filter(username=username)
        if not user:
            if password == confirm_password:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                user = authenticate(username=username, password=password)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return home_view(request)
    return render(request, 'login_page.html')

Movie/templates/account_page.html
{% extends 'base.html' %}

{% block context %}
  <div class="container">
    <h3>Username: {{user.username}}</h3>
    <h3>Account since: {{user.date_joined}}</h3>
    <h2>Your movies</h2>
    <table class="table">
      {% for movie in movies %}
        <tr>
          <td><a href="{% url 'movie:movie' movie.movie.movie_id %}">{{movie.movie.title}}</a></td>
          <td>{{movie.movie.rating}}</td>
        </tr>
      {% endfor %}
    </table>

  </div>
{% endblock %}
{{movie.movie.title}}

Movie/templates/base.html
<HTML>

<HEAD>
    <title>MovieDB</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</HEAD>

<BODY>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar header">
        <a class="navbar-brand">MovieDB</a>
      </div>
      <ul class="nav navbar-nav">
        <li><a href="{% url 'movie:home' %}">Home</a></li>
        <li><a href="{% url 'movie:search' %}">Movies</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {%if user.is_authenticated %}
        <li><a href="{% url 'movie:account' %}">Your account</a></li>
        <li><a href="{% url 'movie:logout' %}">Log out</a></li>
        {%else%}
        <li><a href="{% url 'movie:login'%}">Sign in</a></li>
        {%endif%}
      </ul>
    </div>
  </nav>
  {%block context%}
  {%endblock%}
</BODY>


</HTML>

Movie/templates/home_page.html
{%extends 'base.html'%}

{%block context %}
<div class = "container">
  <div class="row">
    <div class="col-lg-6">
      <h1>Popular Movies</h1>
      <div id="recentCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#recentCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#recentCarousel" data-slide-to="1"></li>
          <li data-target="#recentCarousel" data-slide-to="2"></li>
          <li data-target="#recentCarousel" data-slide-to="3"></li>
          <li data-target="#recentCarousel" data-slide-to="4"></li>
        </ol>

        <div class="carousel-inner">
          {%for item in slideshow %}
            {% if forloop.counter == 1 %}
            <div class="item active">
              <a href="{% url 'movie:movie' item.id %}">
                <img src="{{item.cover_url}}" style="width:100%"/>
              </a>
              <div class="carousel-caption">
                <h3>{{item.title}}</h3>
                <p>{{item.year}}</p>
              </div>
            </div>
            {% else %}
            <div class="item">
              <a href="{% url 'movie:movie' item.id %}">
                <img src="{{item.cover_url}}" style="width:100%"/>
              </a>
              <div class="carousel-caption">
                <h3>{{item.title}}</h3>
                <p>{{item.year}}</p>
              </div>
            </div>
            {% endif %}
          {% endfor %}
          <a class="left carousel-control" href="#recentCarousel" data-slide="prev">
           <span class="glyphicon glyphicon-chevron-left"></span>
           <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#recentCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <h1>Top 20 Movies</h1>
      <table class="table">
        {% for movie in top20 %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td><a href="{% url 'movie:movie' movie.id %}">{{movie.title}}</a></td>
{#            <td>{{movie.year}}</td>#}
            <td>{{movie.rating}}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>

{%endblock%}

Movie/templates/login_page.html
{% extends 'base.html' %}

{% block context %}
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <div>
        Register
        <form action="{% url 'movie:register' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="register_username">Username:</label>
                <input class="form-control" id="register_username" name="register_username"/>
            </div>
            <div class="form-group">
                <label for="register_password">Password:</label>
                <input type="password" class="form-control" id="register_password" name="register_password"/>
            </div>
            <div class="form-group">
                <label for="username">Confirm password:</label>
                <input type="password" class="form-control" id="confirm_password" name="confirm_password"/>
            </div>
            <button class="btn btn-default">Register</button>
        </form>
      </div>
    </div>
    <div class="col-sm-6">
      <div>
        Login
        <form action="{% url 'movie:login'%}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="username">Username:</label>
            <input class="form-control" id="username" name="username"/>
          </div>
          <div class="form-group">
            <label for="username">Password:</label>
            <input type="password" class="form-control" id="password" name="password"/>
          </div>
          <button class="btn btn-default">Login</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Movie/templates/movie_page.html
{% extends 'base.html' %}
{% load static %}
{% block context %}
  <div class="container" style="align-content: center">
    <div class="row">
      <div class="col-lg-3">
        {% if movie.static_cover %}
            <img src="{% static 'static_test.jpg' %}" width="100%"/>
        {% else %}
            <img src="{{movie.cover_url}}" width="100%"/>
        {% endif %}
      </div>
      <div class="col-sm-6">
        <div>
            <h1>{{movie.title}}</h1>
            <h3>{{movie.year}}</h3>
            <h3>{{movie.rating}}</h3>
            <div>
            {% for genre in movie.genres %}
                {{genre}}
            {% endfor %}
            </div>

            <div>
                {{ movie.overview }}
            </div>
        </div>
      </div>
      <div class="col-sm-3">
        {% if user.is_authenticated %}
          {% if is_liked %}
          <form action="{% url 'movie:dislike' movie.id %}">
            <button class="btn btn-default" type="submit">Remove from favourite</button>
          </form>
          {% else %}
          <form action="{% url 'movie:like' movie.id %}">
            <button class="btn btn-default" type="submit">Add to favourite</button>
          </form>
          {% endif %}

        {% else %}
          Sign in for more options
        {% endif%}
      </div>
    </div>
    <div class="container">
        <div class="text-center">
            <h2>Similar movies</h2>
        </div>
        <div class="row">
      {% for movie in similar %}
          <div class="col-sm-4 text-center">
            {% if movie.static_cover %}
                <a href="{% url 'movie:movie' movie.id %}"><img src="{% static 'static_test.jpg' %}" width="50%"/></a>
            {% else %}
                <a href="{% url 'movie:movie' movie.id %}"><img src="{{movie.cover_url}}" width="50%"/></a>
            {% endif %}
          </div>
      {% endfor %}
    </div>
    </div>

  </div>
{% endblock %}

Movie/templates/search_page.html
{%extends 'base.html'%}
{% load static %}
{% block context %}
<!-- Container Searching Form -->
<div class="jumbotron">
  <form class="form-inline text-center" action="{% url 'movie:search' %}" method="GET">
    <div class="form-group">
      <label for="query">Search:</label>
      <input class="form-control" id="query" name="query"/>
    </div>
    <button class="btn btn-default">Search</button>
  </form>
</div>
<!-- End of Searching form container -->

{% if not error %}
<!-- Movie list container -->
<div class="container">
    {% for movie in movies %}
        {% if forloop.counter in start_row %}
            <div class="row" style="margin-top: 10px">
        {% endif %}
                <div class="col-sm-3 text-center" >
                <a href="{% url 'movie:movie' movie.id %}">
                    {% if movie.static_cover %}
                        <img src="{% static 'static_test.jpg' %}" width="100%"/>
                    {% else %}
                        <img src="{{movie.cover_url}}" width="100%"/>
                    {% endif %}
                    <h5>{{ movie.title }}</h5>
                </a>
                </div>
        {% if forloop.counter in end_row %}
            </div>
        {% endif %}
    {% endfor %}
</div>
<!-- End of movie list container -->

<!-- Pagining container -->
<div class="container">
  <ul class="pager">
    {% if page != 1 %}<li class="previous"><a href="{%url 'movie:search'%}?page={{prev_page}}&query={{request.GET.query}}">Previous</a></li>{% endif %}
    {% if page != counter %}<li class="next"><a href="{%url 'movie:search'%}?page={{next_page}}&query={{request.GET.query}}">Next</a></li>{% endif %}
  </ul>
</div>
<!-- End of pagining container -->
{% else %}
<div class="container">
  {{error}}
</div>
{% endif %}
{% endblock %}